### ISSUE TITLE
About text missing

### ISSUE THREAD

**Issue by Alkesst** [melchor629/iTunes-Scrobbler#1]
## Information

 - **macOS version**: 10.13.2
 - **App version**: Pre-release (V 0.1)
 - **Xcode version**: 9.2
 - **Have internet connection?**: internet connection through enterprise proxy

The about app does not show anything useful.

## What you expect the app should behave

is expected to see some useful info about the author of the app. Instead got ```ABOUT_HTML_TEXT```
## Steps to reproduce the issue

Entering the ```About``` page in the scrobbler app.

## Extra

[What I saw](https://goo.gl/sF6ZvF)

**Comment by melchor629** [comment]
Wow, it is not translated into English nor Catalan. Will do it tonight :)
