### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by CheesyWedges** [melchor629/iTunes-Scrobbler#5]
## Information

 - **macOS version**: 10.15.4
 - **App version**:  0.2.3. I downloaded the zip file from the GitHub page
 - **Xcode version**:  - 
 - **Have internet connection?**: Yes

## Description of the issue
After I open the app, Scrobbler icon appears in the menu on top of the desktop.
I log in, authentication part is fine.
After that I go to the Music (formerly iTunes) app, and as soon as I start to play song, the Scrobbler app crashes? closes. It no longer appears in the tool bar. I have to re-open again. Same thing happens when I start another song.

## What you expect the app should behave

It shouldn't crash and scrobble.

## Steps to reproduce the issue

No idea, bro.

## Crash log

No error msg appears.

## Extra

None. Thanks for this. I've used it before without any issues.

**Comment by CheesyWedges** [comment]
App version is 0.2.3

**Comment by CheesyWedges** [comment]
I see that there's a new version 0.3.3, but I can't find an installer.

**Comment by melchor629** [comment]
Hi, there is no installer, just download the [zip release](https://github.com/melchor629/iTunes-Scrobbler/releases/download/v0.3.4/iTunes.Scrobbler.zip), extract it and replace the current version. Newer versions updates itself alone and notifies you if there is an error or was successful with the update.

Well, try the `0.3.3` version, it should work, but if not, comment it here. Feel free to close the issue if everything is fine :)

**Comment by CheesyWedges** [comment]
Thanks man! :)
Will try and let you know what happens.

**Comment by CheesyWedges** [comment]
Works perfectly.
Love this, man.
Many thanks (from Maldives).

**Comment by melchor629** [comment]
Cool, glad to hear it is now working :)
Thanks to you for enjoying the app.
