### ISSUE TITLE
App crashes a few seconds after opening

### ISSUE THREAD

**Issue by CheesyWedges** [melchor629/iTunes-Scrobbler#6]
## Information

 - **macOS version**: MacOS Big Sur 11.0.1
 - **App version**:  0.3.4
 - **Xcode version**: N/A
 - **Have internet connection?**: Yes

## Description of the issue

I open the app, the icon appears in the menu bar, then 2 seconds later, it's gone. I've to reopen the app again; same thing happens.

## What you expect the app should behave

I expect the app not to crash.

## Steps to reproduce the issue

N/A

## Crash log

No log is shown.

## Extra

Thanks for the great app, bro. Love it. If there's a new stable version, can u pls post the link to the .dmg file?

**Comment by melchor629** [comment]
Hi, it's difficult to investigate a crash without any logs or crash reports :( Yet I was preparing a new version of the app, and it's published. Give it a try and come back with the results.

**Comment by CheesyWedges** [comment]
[iTunes Scrobbler.2020.11.20.log](https://github.com/melchor629/iTunes-Scrobbler/files/5577383/iTunes.Scrobbler.2020.11.20.log)
[iTunes Scrobbler.2020.11.21.log](https://github.com/melchor629/iTunes-Scrobbler/files/5577384/iTunes.Scrobbler.2020.11.21.log)

I just found out how to find the logs. Find attached the log from today and yesterday. Hope this helps.

**Comment by melchor629** [comment]
Sadly, logs here does not say anything :(

A crash report would be nice. They can be found in "Console" app (they are generated by macOS itself).

Anyway, if you could try the latest version meanwhile and check if it still crashes for you...

**Comment by CheesyWedges** [comment]
Found the crash reports too. (Sorry I'm not very familiar with finding logs and crash reports, that's why wasn't able to send previously.)

[Archive.zip](https://github.com/melchor629/iTunes-Scrobbler/files/5577413/Archive.zip)

Hope this helps.

**Comment by CheesyWedges** [comment]
Same thing happens with the newest release (version 0.4.0). 
It is crashing a few seconds after opening.

**Comment by melchor629** [comment]
Do not worry, nobody needs to know how to extract logs :) (I should update the issue template and add all this information hehe).

With the crash reports, I could find what is causing the crash. For some reason (something I suspected from your logs), it is the updater that crashes. Still I don't know what is causing the updater to fail, but it's something.

**Comment by melchor629** [comment]
Well, I refactored the updater a bit so if it fails, instead of crash, log something (I hope this is the fix you need). Below there is a beta of the change. Whenever you can, give it a try and tell me if it works. For some reason I cannot replicate your issue so, if you don't mind, you'll be the tester :)
[iTunes Scrobbler.zip](https://github.com/melchor629/iTunes-Scrobbler/files/5577539/iTunes.Scrobbler.zip)

If it does not crash, would be nice to send me the latest log file to inspect what is going on...

**Comment by CheesyWedges** [comment]
Just tested the new version in the link. Still crashing.

Here are the crash reports and the log. 

[Log and Crash Reports.zip](https://github.com/melchor629/iTunes-Scrobbler/files/5579037/Log.and.Crash.Reports.zip)

**Comment by melchor629** [comment]
Thanks for the logs and crash reports. Now I may have a more concise idea of the error (I believe). See below a new version with the (I hope) fix 🤞 
[iTunes Scrobbler.zip](https://github.com/melchor629/iTunes-Scrobbler/files/5579232/iTunes.Scrobbler.zip)

**Comment by CheesyWedges** [comment]
Perfect. Problem solved 👍 
Thank you so much for your work.

**Comment by melchor629** [comment]
Really glad to see this is now fixed properly :D

I will upload everything now and create a new version so nobody will experience this anymore. And thanks to you by raising the issue and helping me find the issue.
